dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.7"
 env:
  global:
    - CC_TEST_REPORTER_ID=764857e104022c3b87e0052bf9a25aa4ffa5c36fecc38ca35f3772edb9ecfc79

install:
  - "pip install pytest"               # install pytest
  - "pip install pytest-cov"           # This plugin produces coverage reports
  - "pip install codecov"              # install codecov
  - "pip install codacy-coverage"      # Install codacy-coverage
  - "pip install -r requirements.txt"  # Needed mainly for making Allure work

before_script:  # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # Run pytest for all tests subdirectories and check test coverage with pytest-cov:
  - pytest --cov-config=.coveragerc --cov-report term-missing --cov
  - mypy --ignore-missing-imports kyu_8
  - mypy --ignore-missing-imports kyu_7
  - mypy --ignore-missing-imports kyu_6
  - mypy --ignore-missing-imports kyu_5
  - mypy --ignore-missing-imports kyu_4
  - mypy --ignore-missing-imports utils

after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - codecov
  # python codacy coverage
  # Source: https://github.com/codacy/python-codacy-coverage
  - python-codacy-coverage -r coverage.xml
