dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.7"

install:
  - "pip install pytest"          # install pytest
  - "pip install pytest-cov"      # This plugin produces coverage reports
  - "pip install codecov"         # install codecov
  - "pip install codacy-coverage" # Install codacy-coverage

script:
  # Run pytest for all tests subdirectories and check test coverage with pytest-cov:
  - pytest --cov-config=.coveragerc --cov-report term-missing --cov
  - coverage report && coverage xml && python-codacy-coverage -r coverage.xml

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - codecov